all:
  children:
    customer_a:          # 顧客グループ（顧客共通変数の層として使う）
      children:
        web:             # 役割グループ（プレイブックは hosts: web で指定）
          hosts:
            # 命名規則: <顧客略称>-<環境略称>-<役割><連番>
            # ca-prd-web01:
            #   ansible_host: 192.0.2.10
            ca-prd-web01:
              ansible_host: 127.0.0.1
              ansible_user: ec2-user
              ansible_port: 2210
            # ca-prd-web02:
            #   ansible_host: 192.0.2.11
            ca-prd-web02:
              ansible_host: 127.0.0.1
              ansible_user: ec2-user
              ansible_port: 2211
        db:
          hosts:
            # ca-prd-db01:
            #   ansible_host: 192.0.2.20
            ca-prd-db01:
              ansible_host: 127.0.0.1
              ansible_user: ec2-user
              ansible_port: 2212
