all:
  children:
    customer_b:          # 顧客グループ（顧客共通変数の層として使う）
      children:
        web:             # 役割グループ（プレイブックは hosts: web で指定）
          hosts:
            # 命名規則: <顧客略称>-<環境略称>-<役割><連番>
            cb-stg-web01:
              ansible_host: 127.0.0.1
              ansible_user: ec2-user
              ansible_port: 2250
        db:
          hosts:
            cb-stg-db01:
              ansible_host: 127.0.0.1
              ansible_user: ec2-user
              ansible_port: 2251
