all:
  children:
    customer_a:          # 顧客グループ（顧客共通変数の層として使う）
      children:
        web:             # 役割グループ（プレイブックは hosts: web で指定）
          hosts:
            # 命名規則: <顧客略称>-<環境略称>-<役割><連番>
            # ca-stg-web01:
            #   ansible_host: 192.0.10.10
            ca-stg-web01:
              ansible_host: 127.0.0.1
              ansible_user: ec2-user
              ansible_port: 2230
        db:
          hosts:
            # ca-stg-db01:
            #   ansible_host: 192.0.10.20
            ca-stg-db01:
              ansible_host: 127.0.0.1
              ansible_user: ec2-user
              ansible_port: 2231